SELECT CITY, LENGTH(CITY)
FROM (SELECT *
      FROM STATION
      ORDER BY LENGTH(CITY) ASC, CITY ASC LIMIT 1) x
UNION ALL
SELECT CITY, LENGTH(CITY)
FROM (SELECT *
      FROM STATION
      ORDER BY LENGTH(CITY) DESC, CITY ASC LIMIT 1) y;